#ifndef PIXELCOLUMNPROCESSRETURN_T_H
#define PIXELCOLUMNPROCESSRETURN_T_H

enum PixelColumnProcessingReturn_t {PCP_OK, PCP_FAILED_MAX_TII, PCP_FAILED_MAT_TYPE, PCP_FAILED_COLUMN_OUT_OF_RANGE};

#endif // PIXELCOLUMNPROCESSRETURN_T_H


